### ISSUE TITLE
How to save daily steps?

### ISSUE THREAD

**Issue by tndevDE** [akaboshinit/pedometer_plus#2]
I am currently trying to learn Flutter. My start app for learning should be an app for iOS and Android that saves the daily steps and then I would like to add more and more functions. But unfortunately I don't understand how this is supposed to work. I've been trying to read up on it for a few days, but I can't get any results. Could you please show me how I can save the daily steps, perhaps with an example? Thank you very much and sorry for the stupid question.

**Comment by Flucadetena** [comment]
Hey @tndevDE did you manage to find a solution?

**Comment by tndevDE** [comment]
Hi @Flucadetena, no I haven't yet, but I think I will switch to the health package. (I haven't had time for my project at the moment)

**Comment by Flucadetena** [comment]
Hi @tndevDE Sorry for the late response. I've done some research and it looks like it is not posible on Android, as the native api does not allow it. In IOS you can do it, as this package allows you.

But on android is only posible though the `health api`. That you can use with the package you mentioned.

If that is essential, use it, it is very good. Although I warn you the problems with users is high. Many users have problems with permissions, connections. When they have multiple accounts connected to Google Fit is complicated.
And take into account Android now kills GoogleFit when goes into "Battery saving mode" or "Extreme saving mode" depending on the model. So no data will be recover and they have to enter GF back after.

Hope this info helps you with support.

If you still need help implementing this package let me know and I'll drop some code.

**Comment by tndevDE** [comment]
Hi @Flucadetena, thank you very much for the detailed answer, that helps me a lot. 

I've run into problems developing for Android several times now, so I'm going to develop the app for iOS only for now and I actually want to create a pleasant user experience and only need the pedometer, so I'll continue to create the app with your package. 

Would you still help me with my question above?

**Comment by Flucadetena** [comment]
Hey @tndevDE I'm you are having this experience in your first project. I promise you it is not always like this ;)

Just to be clear, this is not my package. But we use it and we are testing a lot of things in it so I'll be happy to help.

If you are only going to use it in IOS you have to options. 
1.- You can just retrieve the the amount of steps between to dates. In you case you could get the steps for yesterday for example, or the number of steps so far today.

*To manage DateTimes in this cases we have created some extensions, but you can use some other ways or packages if you prefer. I just added the extension here at the bottom so you can understand the code well.
```
 void getTotalSteps() async {
  final _pedometer = Pedometer();
  
  final now = DateTime.now();
  DateTime yesterday = now.subtract(const Duration(days: 1));

   int yesterdaySteps = await _pedometer.getStepCount(from: yesterday.startOfDay, to: yesterday.endOfDay);
   print('Steps from yesterday: ${yesterdaySteps}');
   int todaySteps = await _pedometer.getStepCount(from: now.startOfDay, to: now.endOfDay);
   print('Steps so far today: ${todaySteps}');
}

extension ExtendDateTime on DateTime {
  DateTime get startOfDay => DateTime(year, month, day);
  DateTime get endOfDay => DateTime(year, month, day, 23, 59, 59);
}
```

2.- You can also get an stream of the steps taken since a date until now. Getting updates when the user keeps walking.
*Take into consideration this is an stream. So be sure to dispose of it when the widget is destroyed. So if you are using an StatefulWidget, do it in the dispose method.
```
  @override
  void dispose() {
    _stepCountStreamSubscription.cancel();
    super.dispose();
  }

// This prints the steps in the last 24h and then keeps updating as long as the app is open in this screen
void listenToStepsInLastDay(){
   _stepCountStreamSubscription = _pedometer.stepCountStreamFrom(from: DateTime(2024, 5, 16)).listen((steps) {
        print('Number of steps: ${steps}');
   });
}
```
 
Hope this helps, If you need help with anything else let me know and i'll try to help whenever i can ;)

**Comment by tndevDE** [comment]
Thank you for the answer, I will try it out in a few days

**Comment by Flucadetena** [comment]
Hey @tndevDE due to my need to use this package or the original pedometer version with improved functionality I've created a package and added it to pub.dev.

I've added functionality to Android and now you can query the same on iOS and Android with improved accuracy.

If you want to test it an give me feedback it would be awesome. Hope it helps with your project, if you have any questions or requests don't hesitate to write an issue or discussion on the repo of the new package.

This is the link to pub: [Pedometer_2](https://pub.dev/packages/pedometer_2). You have very detailed info on how to set it up and how to use it. ;)

**Comment by tndevDE** [comment]
Hey @Flucadetena, this looks very nice, I will try it out. 
Thank you very much
